required_directories:
    - src
    - tests
required_files:
    - setup.cfg
    - pyproject.toml
    - scene_attributes_train.csv
    - scene_attributes_test.csv
optional_directories:
    - additional_data
optional_files:
    - README.txt
